collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
color:
  saturation: 0.5214823
  brandStrength: 0.2003222
  lightness: 0.3066595
  brandColors:
    - '#C7AA80'
    - '#390C0E'
    - '#FBFFFF'
    - '#896C4B'
    - '#5C91FA'
  rhythmicContrast: 0.4033297
typography_spectrum: 0.06928033
layout_spectrum: 0.7008593
name: Roll On Painting
