collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    feed:
      path: /rss.xml
      format: rss
      number: 10
    permalink:
      path: '/:title/'
typography_spectrum: 0.06928033
color:
  saturation: 0.7320086
  brandStrength: 0.2003222
  lightness: 1
  brandColors:
    - '#CEDED1'
    - '#30CFFF'
    - '#0D161E'
    - '#036EA2'
    - '#64706D'
  rhythmicContrast: 0.9382384
layout_spectrum: 0.8641245
name: Roll On Painting
